### ISSUE TITLE
[BUG] org.opensearch.ad.transport.AnomalyDetectorJobTransportActionTests > testStartHistoricalAnalysisForMultiCategoryHCWithUser fails on JDK8

### ISSUE THREAD

**Issue by dblock** [opensearch-project/anomaly-detection#426]
**Describe the bug**

org.opensearch.ad.transport.AnomalyDetectorJobTransportActionTests > testStartHistoricalAnalysisForMultiCategoryHCWithUser fails on JDK8 consistently, https://github.com/opensearch-project/anomaly-detection/runs/5503031967?check_suite_focus=true. Not reproduced locally, so is repeatable because the hardware is slow. Don't expect a test to depend on that to pass.  

```
2022-03-10T22:01:06.8901915Z org.opensearch.ad.transport.AnomalyDetectorJobTransportActionTests > testStartHistoricalAnalysisForMultiCategoryHCWithUser FAILED
2022-03-10T22:01:06.8902617Z     java.lang.AssertionError
2022-03-10T22:01:06.8903426Z         at __randomizedtesting.SeedInfo.seed([CC9B1EF17C496801:569347FFB390D8A9]:0)
2022-03-10T22:01:06.8903812Z         at org.junit.Assert.fail(Assert.java:87)
2022-03-10T22:01:06.8904366Z         at org.junit.Assert.assertTrue(Assert.java:42)
2022-03-10T22:01:06.9076036Z         at org.junit.Assert.assertTrue(Assert.java:53)
2022-03-10T22:01:06.9076836Z         at org.opensearch.ad.transport.AnomalyDetectorJobTransportActionTests.testStartHistoricalAnalysisForMultiCategoryHCWithUser(AnomalyDetectorJobTransportActionTests.java:237)
2022-03-10T22:02:24.6907583Z REPRODUCE WITH: ./gradlew ':test' --tests 
```

**Comment by ylwu-amzn** [comment]
Close this one, track all flaky test in this meta issue https://github.com/opensearch-project/anomaly-detection/issues/499
