### ISSUE TITLE
[BUG] org.opensearch.ad.transport.ADBatchAnomalyResultTransportActionTests.testMultipleTasks fails on JDK8

### ISSUE THREAD

**Issue by dblock** [opensearch-project/anomaly-detection#427]
**Describe the bug**

Similar to #426.

```
  2> REPRODUCE WITH: ./gradlew ':test' --tests "org.opensearch.ad.transport.ADBatchAnomalyResultTransportActionTests.testMultipleTasks" -Dtests.seed=CC9B1EF17C496801 -Dtests.security.manager=false -Dtests.locale=es-AR -Dtests.timezone=America/Mexico_City -Druntime.java=8
  2> REPRODUCE WITH: ./gradlew ':test' --tests "org.opensearch.ad.transport.ADBatchAnomalyResultTransportActionTests.testMultipleTasks" -Dtests.seed=CC9B1EF17C496801 -Dtests.security.manager=false -Dtests.locale=es-AR -Dtests.timezone=America/Mexico_City -Druntime.java=8
  2> org.gradle.internal.exceptions.DefaultMultiCauseException: Multiple Failures (2 failures)
    	java.lang.AssertionError: <no message>
    	com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=5743, name=opensearch[node_t4][ad-batch-task-threadpool][T#1], state=RUNNABLE, group=TGRP-ADBatchAnomalyResultTransportActionTests]
        at org.junit.vintage.engine.execution.TestRun.getStoredResultOrSuccessful(TestRun.java:196)
        at org.junit.vintage.engine.execution.RunListenerAdapter.fireExecutionFinished(RunListenerAdapter.java:226)
        at org.junit.vintage.engine.execution.RunListenerAdapter.testFinished(RunListenerAdapter.java:192)
        at org.junit.vintage.engine.execution.RunListenerAdapter.testFinished(RunListenerAdapter.java:79)
        at org.junit.runner.notification.SynchronizedRunListener.testFinished(SynchronizedRunListener.java:87)
        at org.junit.runner.notification.RunNotifier$9.notifyListener(RunNotifier.java:225)
        at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
        at org.junit.runner.notification.RunNotifier.fireTestFinished(RunNotifier.java:222)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$SubNotifier.fireTestFinished(ThreadLeakControl.java:202)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:956)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
        at com.carrotsearch.randomizedtesting.rules.NoShadow
```

**Comment by ylwu-amzn** [comment]
Close this one, track all flaky test in this meta issue https://github.com/opensearch-project/anomaly-detection/issues/499
