### ISSUE TITLE
[1.3.0][integtest] IntegTest failed with security on 1.3.0

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/anomaly-detection#430]
@ohltyler 
```
2022-03-10 23:20:27 ERROR    | anomaly-detection    | with-security        | FAIL  |    1 |
```
I have seen failures in AD BE plugin.
```
2022-03-10 22:43:38 INFO     ===============================================
2022-03-10 22:43:38 INFO     Running integration tests for anomaly-detection
2022-03-10 22:43:38 INFO     ===============================================
2022-03-10 22:43:38 INFO     Executing "/var/jenkins/workspace/integ-test/scripts/default/integtest.sh -b localhost -p 9200 -s true -v 1.3.0" in /tmp/tmp9obfk_vn/anomaly-detection
2022-03-10 22:59:52 INFO     Recording component test results for anomaly-detection at /var/jenkins/workspace/integ-test/test-results/016a8b0fee7549b2adef1a414f34381f/integ-test/anomaly-detection/with-security/test-results
2022-03-10 22:59:52 INFO     Integration test run failed for component anomaly-detection
2022-03-10 22:59:52 INFO     Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /tmp/tmp9obfk_vn/anomaly-detection/src/test/java/org/opensearch/action/admin/indices/mapping/get/IndexAnomalyDetectorActionHandlerTests.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

REPRODUCE WITH: ./gradlew ':integTest' --tests "org.opensearch.ad.rest.SecureADRestIT.testUpdateApiFilterByEnabled" -Dtests.seed=880872AD65C32DB6 -Dtests.security.manager=false -Dtests.locale=zh-SG -Dtests.timezone=Pacific/Port_Moresby -Druntime.java=14

REPRODUCE WITH: ./gradlew ':integTest' --tests "org.opensearch.ad.rest.SecureADRestIT.testCreateAnomalyDetectorWithCustomResultIndex" -Dtests.seed=880872AD65C32DB6 -Dtests.security.manager=false -Dtests.locale=zh-SG -Dtests.timezone=Pacific/Port_Moresby -Druntime.java=14

Suite: Test class org.opensearch.ad.rest.SecureADRestIT
  2> 三月 11, 2022 8:53:59 上午 org.opensearch.client.RestClient logResponse
  2> WARNING: request [PUT https://localhost:9200/_cluster/settings] returned 1 warnings: [299 OpenSearch-1.3.0-e45991597c86ba1bbcc36ee1dfdc165197a913af "[opendistro.anomaly_detection.filter_by_backend_roles] setting was deprecated in OpenSearch and will be removed in a future release! See the breaking changes documentation for the next major version."]
  2> REPRODUCE WITH: ./gradlew ':integTest' --tests "org.opensearch.ad.rest.SecureADRestIT.testUpdateApiFilterByEnabled" -Dtests.seed=880872AD65C32DB6 -Dtests.security.manager=false -Dtests.locale=zh-SG -Dtests.timezone=Pacific/Port_Moresby -Druntime.java=14
  2> org.opensearch.client.ResponseException: method [PUT], host [https://localhost:9200], URI [/_plugins/_anomaly_detection/detectors/tW8Mdn8BlBe6AXa6GCf9], status line [HTTP/1.1 500 Internal Server Error]
    {"error":{"root_cause":[{"type":"status_exception","reason":"Timestamp field: (mALlZ) is not found in index mapping"}],"type":"status_exception","reason":"Timestamp field: (mALlZ) is not found in index mapping"},"status":500}
        at __randomizedtesting.SeedInfo.seed([880872AD65C32DB6:DCC08CB6914F2B73]:0)
        at org.opensearch.client.RestClient.convertResponse(RestClient.java:344)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:314)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:289)
        at org.opensearch.ad.TestHelpers.makeRequest(TestHelpers.java:211)
        at org.opensearch.ad.TestHelpers.makeRequest(TestHelpers.java:184)
        at org.opensearch.ad.TestHelpers.makeRequest(TestHelpers.java:173)
        at org.opensearch.ad.AnomalyDetectorRestTestCase.updateAnomalyDetector(AnomalyDetectorRestTestCase.java:213)
        at org.opensearch.ad.rest.SecureADRestIT.testUpdateApiFilterByEnabled(SecureADRestIT.java:224)
  2> REPRODUCE WITH: ./gradlew ':integTest' --tests "org.opensearch.ad.rest.SecureADRestIT.testCreateAnomalyDetectorWithCustomResultIndex" -Dtests.seed=880872AD65C32DB6 -Dtests.security.manager=false -Dtests.locale=zh-SG -Dtests.timezone=Pacific/Port_Moresby -Druntime.java=14
  2> org.opensearch.client.ResponseException: method [POST], host [https://localhost:9200], URI [/_plugins/_anomaly_detection/detectors], status line [HTTP/1.1 500 Internal Server Error]
    {"error":{"root_cause":[{"type":"status_exception","reason":"Timestamp field: (vVcCO) is not found in index mapping"}],"type":"status_exception","reason":"Timestamp field: (vVcCO) is not found in index mapping"},"status":500}
        at __randomizedtesting.SeedInfo.seed([880872AD65C32DB6:148A03D11EE27876]:0)
        at org.opensearch.client.RestClient.convertResponse(RestClient.java:344)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:314)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:289)
        at org.opensearch.ad.TestHelpers.makeRequest(TestHelpers.java:211)
        at org.opensearch.ad.TestHelpers.makeRequest(TestHelpers.java:184)
        at org.opensearch.ad.AnomalyDetectorRestTestCase.createAnomalyDetector(AnomalyDetectorRestTestCase.java:129)
        at org.opensearch.ad.rest.SecureADRestIT.testCreateAnomalyDetectorWithCustomResultIndex(SecureADRestIT.java:317)
  2> NOTE: leaving temporary files on disk at: /tmp/tmp9obfk_vn/anomaly-detection/build/testrun/integTest/temp/org.opensearch.ad.rest.SecureADRestIT_880872AD65C32DB6-001
  2> NOTE: test params are: codec=Lucene87, sim=Asserting(RandomSimilarity(queryNorm=true): {}), locale=zh-SG, timezone=Pacific/Port_Moresby
  2> NOTE: Linux 4.14.243-185.433.amzn2.aarch64 aarch64/AdoptOpenJDK 14.0.2 (64-bit)/cpus=16,threads=1,free=308052304,total=536870912
  2> NOTE: All tests run in this JVM: [AnomalyDetectorRestApiIT, HistoricalAnalysisRestApiIT, SecureADRestIT]

95 tests completed, 2 failed, 1 skipped

=== Standard output of node `node{::integTest-0}` ===

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':integTest'.
> There were failing tests. See the report at: file:///tmp/tmp9obfk_vn/anomaly-detection/build/reports/tests/integTest/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16m 14s
```

**Comment by ylwu-amzn** [comment]
Can reproduce the failure on desktop. My test step:
1. Download this tarball to my desktop
2. Unzip the tarball and install to start a local cluster
3. Git clone latest 1.3 AD code. Run `./gradlew integTest -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername="docker-cluster" -Dhttps=true -Duser=admin -Dpassword=admin`
