### ISSUE TITLE
[BUG] testRaceConditionByStartingMultipleTasks is flakey

### ISSUE THREAD

**Issue by dblock** [opensearch-project/anomaly-detection#442]
org.opensearch.ad.transport.AnomalyDetectorJobTransportActionTests.testRaceConditionByStartingMultipleTasks

https://github.com/opensearch-project/anomaly-detection/runs/5555077107?check_suite_focus=true

```
org.opensearch.ad.transport.AnomalyDetectorJobTransportActionTests > testRaceConditionByStartingMultipleTasks FAILED
REPRODUCE WITH: ./gradlew ':test' --tests "org.opensearch.ad.transport.AnomalyDetectorJobTransportActionTests.testRaceConditionByStartingMultipleTasks" -Dtests.seed=C58852756DCF8696 -Dtests.security.manager=false -Dtests.locale=es-MX -Dtests.timezone=Pacific/Norfolk -Druntime.java=14
    java.lang.AssertionError: Values should be different. Actual: FAILED
        at __randomizedtesting.SeedInfo.seed([C58852756DCF8696:368E8C597708C62A]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failEquals(Assert.java:187)
        at org.junit.Assert.assertNotEquals(Assert.java:163)
        at org.junit.Assert.assertNotEquals(Assert.java:177)
        at org.opensearch.ad.transport.AnomalyDetectorJobTransportActionTests.testRaceConditionByStartingMultipleTasks(AnomalyDetectorJobTransportActionTests.java:306)

  1> [2022-03-16T02:26:14,882][INFO ][o.o.a.t.AnomalyDetectorJobTransportActionTests] [testRunMultipleTasksForHistoricalAnalysis] before test
  1> [2022-03-16T02:26:14,883][INFO ][o.o.a.t.AnomalyDetectorJobTransportActionTests] [testRunMultipleTasksForHistoricalAnalysis] [AnomalyDetectorJobTransportActionTests#testRunMultipleTasksForHistoricalAnalysis]: setting up test
  1> [2022-03-16T02:26:14,883][INFO ][o.o.t.InternalTestCluster] [testRunMultipleTasksForHistoricalAnalysis] Setup InternalTestCluster [TEST-TEST_WORKER_VM=[2]-CLUSTER_SEED=[49858[927](https://github.com/opensearch-project/anomaly-detection/runs/5555077107?check_suite_focus=true#step:5:927)30996153785]-HASH=[B7406E94C5]-cluster] with seed [45317305BF3A5DB9] using [0] dedicated masters, [2] (data) nodes and [0] coord only nodes (min_master_nodes are [auto-managed])
```

**Comment by ylwu-amzn** [comment]
Close this one, track all flaky test in this meta issue https://github.com/opensearch-project/anomaly-detection/issues/499
