### ISSUE TITLE
[BUG] Flaky Test AnomalyDetectorJobTransportActionTests.testStartHistoricalAnalysisForMultiCategoryHCWithUser() on JDK 11

### ISSUE THREAD

**Issue by amitgalitz** [opensearch-project/anomaly-detection#448]
**Describe the bug**
`org.opensearch.ad.transport.AnomalyDetectorJobTransportActionTests.testStartHistoricalAnalysisForMultiCategoryHCWithUser` is flaky on JDK 11, it consistently fails on JDK8 as mentioned here (#426). This isn't reproducible locally and is probably due to Github action runners being too slow.
https://github.com/opensearch-project/anomaly-detection/runs/5576819081?check_suite_focus=true
```
REPRODUCE WITH: ./gradlew ':test' --tests "org.opensearch.ad.transport.AnomalyDetectorJobTransportActionTests.testStartHistoricalAnalysisForMultiCategoryHCWithUser" -Dtests.seed=7D8178FC2A1DEFDD -Dtests.security.manager=false -Dtests.locale=pt-PT -Dtests.timezone=Asia/Chita -Druntime.java=11
  2> REPRODUCE WITH: ./gradlew ':test' --tests "org.opensearch.ad.transport.AnomalyDetectorJobTransportActionTests.testStartHistoricalAnalysisForMultiCategoryHCWithUser" -Dtests.seed=7D8178FC2A1DEFDD -Dtests.security.manager=false -Dtests.locale=pt-PT -Dtests.timezone=Asia/Chita -Druntime.java=11
  2> org.gradle.internal.exceptions.DefaultMultiCauseException: Multiple Failures (2 failures)
    	java.lang.AssertionError: <no message>
    	com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=3002, name=opensearch[node_t1][ad-batch-task-threadpool][T#1], state=RUNNABLE, group=TGRP-AnomalyDetectorJobTransportActionTests]
        at org.junit.vintage.engine.execution.TestRun.getStoredResultOrSuccessful(TestRun.java:196)
        at org.junit.vintage.engine.execution.RunListenerAdapter.fireExecutionFinished(RunListenerAdapter.java:226)
        at org.junit.vintage.engine.execution.RunListenerAdapter.testFinished(RunListenerAdapter.java:192)
        at org.junit.vintage.engine.execution.RunListenerAdapter.testFinished(RunListenerAdapter.java:79)
        at org.junit.runner.notification.SynchronizedRunListener.testFinished(SynchronizedRunListener.java:87)
        at org.junit.runner.notification.RunNotifier$9.notifyListener(RunNotifier.java:225)
        at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
        at org.junit.runner.notification.RunNotifier.fireTestFinished(RunNotifier.java:222)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$SubNotifier.fireTestFinished(ThreadLeakControl.java:202)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:956)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at java.base/java.lang.Thread.run(Thread.java:829)

        Caused by:
        java.lang.AssertionError
            at org.junit.Assert.fail(Assert.java:87)
            at org.junit.Assert.assertTrue(Assert.java:42)
            at org.junit.Assert.assertTrue(Assert.java:53)
```

**Comment by minalsha** [comment]
@amitgalitz  what is the latest update on this issue? Thanks

**Comment by minalsha** [comment]
@jackiehanyang  what is the status of this bug?
